/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ryszard.jenvey' at '01/05/15 11:58' with Gradle 2.3
 *
 * @author ryszard.jenvey, @date 01/05/15 11:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
